### ISSUE TITLE
old versions of the gem on rubygems.org

### ISSUE THREAD

**Issue by xblitz** [ruby/English#1]
Hi guys,  it seems that this repo now provides the gem for https://rubygems.org/gems/english/ but the old versions (that were coming from https://github.com/rubyworks/english)  have been yanked, and Im seeing this break several integrations in multiple projects, and also as the "github" link on the gem's page still points to the old repo , which made me originally think it might be a hacked version of the gem. 

If this new gem fully replaces the old one, any reason to yank the old versions?

**Comment by hsbt** [comment]
Did you face the problem at `sensu-plugins-process-checks`?

**Comment by xblitz** [comment]
my specific case is related to https://github.com/sensu-plugins/sensu-plugins-java/issues/41 actually,  and I have a colleague that had issue with something related to chef

**Comment by hsbt** [comment]
In historical reason, the namespace of english was takeover rubygems.org and ruby core team over the 5 years ago. and English-0.6.3 is completely different library with this repository. I need to yank it for that avoid to confusion for users.

In my investigation, `sensu-plugins-process-checks` relied on the code of this repository, not https://github.com/rubyworks/english. So, the original author misunderstood to usage of english gem.

Like https://github.com/sensu-plugins/sensu-plugins-process-checks/blob/master/bin/check-cmd.rb#L29, There is no `plural` methods, only `:CHILD_STATUS`. `:CHILD_STATUS` is provided by `English.rb` of this repository.

So, https://github.com/sensu-plugins/sensu-plugins-process-checks/releases/tag/4.2.0 is finally works fine. `sensu-plugins-java` must upgrade to `English-0.7.0`

**Comment by xblitz** [comment]
thank you for the details!

**Comment by hsbt** [comment]
@xblitz Also Thank you for notifying to me.
